# Setup
title:        zt blog
baseurl:      ""

# About/contact
author:
  name:       一只假的大白
  url:        https://eleanore8.github.io/

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown